services:
  solr:
    image: solr:9
    container_name: solr
    restart: unless-stopped
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - demo
volumes:
  solr_data:
